apiVersion: apps/v1
kind: Deployment
metadata:
  name: datawai-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: datawai-api
  template:
    metadata:
      labels:
        app: datawai-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: APP_PORT
              value: {{ .Values.service.port | quote }}
