import { useState } from 'react';
import type { FormEvent } from 'react';
import { Alert, Button, Card, Input, PageHeader, Select } from '../components/ui';
import PremiumGate from '../components/PremiumGate';
import { usePortal } from '../contexts/PortalContext';

export default function Policies() {
  const { invalidatePremium } = usePortal();
  const [step, setStep] = useState(1); const [error, setError] = useState(''); const [output, setOutput] = useState(''); const [loading, setLoading] = useState(false);
  const [form, setForm] = useState({ businessName: '', contactEmail: '', dataTypes: '', thirdParties: '', retentionMonths: '24' });
  const validateStep = () => {
    if (step === 1 && (form.businessName.trim().length < 2 || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.contactEmail))) return 'Enter a business name and valid privacy contact email.';
    if (step === 2 && form.dataTypes.trim().length < 2) return 'Describe the personal data categories collected.';
    if (step === 3 && form.thirdParties.trim().length < 2) return 'Describe processors and third parties, or state that none are used.';
    return '';
  };
  const next = () => { const message = validateStep(); setError(message); if (!message) setStep((current) => current + 1); };
  const generate = async (event: FormEvent) => { event.preventDefault(); setLoading(true); setError(''); try { const response = await fetch(`${import.meta.env.VITE_API_URL}/api/policies/generate`, { credentials: 'include', method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, retentionMonths: Number(form.retentionMonths) }) }); if (response.status === 403) invalidatePremium(); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'The policy could not be generated.'); setOutput(data.policy); setStep(6); } catch (caught) { setError(caught instanceof Error ? caught.message : 'The policy could not be generated.'); } finally { setLoading(false); } };
  const field = (id: string, label: string, value: string, onChange: (value: string) => void, type = 'text', maxLength = 2000) => <div><label htmlFor={id}>{label}</label><Input id={id} type={type} value={value} onChange={(event) => onChange(event.target.value)} required maxLength={maxLength} aria-describedby={error ? 'policy-error' : undefined} /></div>;
  return <><PageHeader eyebrow="Guided workspace" title="Policy generator" description="Generate a working draft from information you provide. The output supports your compliance process and is not a legal guarantee." /><PremiumGate><Card className="workspace-card policy-workflow"><ol className="workflow-steps" aria-label="Policy generation progress">{['Business details', 'Data collected', 'Processors', 'Retention', 'Generate', 'Review'].map((label, index) => <li className={step === index + 1 ? 'is-active' : step > index + 1 ? 'is-complete' : ''} key={label}>{index + 1}. {label}</li>)}</ol>{error && <div id="policy-error"><Alert tone="danger">{error}</Alert></div>}{step === 6 ? <div><h2>Review your generated draft</h2><pre className="policy-output">{output}</pre><Button onClick={() => { void navigator.clipboard.writeText(output); }}>Copy policy</Button></div> : <form onSubmit={generate} className="guided-form">{step === 1 && <>{field('policy-business-name', 'Business or legal entity name', form.businessName, (businessName) => setForm({ ...form, businessName }), 'text', 200)}{field('policy-contact-email', 'Privacy contact email', form.contactEmail, (contactEmail) => setForm({ ...form, contactEmail }), 'email', 254)}</>}{step === 2 && field('policy-data-types', 'Personal data categories collected', form.dataTypes, (dataTypes) => setForm({ ...form, dataTypes }))}{step === 3 && field('policy-third-parties', 'Processors and third parties', form.thirdParties, (thirdParties) => setForm({ ...form, thirdParties }))}{step === 4 && <div><label htmlFor="policy-retention">Retention period</label><Select id="policy-retention" value={form.retentionMonths} onChange={(event) => setForm({ ...form, retentionMonths: event.target.value })}><option value="12">12 months</option><option value="24">24 months</option><option value="36">36 months</option></Select></div>}{step === 5 && <div><h2>Generate your working draft</h2><p className="muted">Review the details you supplied before generating.</p></div>}<div className="form-actions">{step > 1 && <Button type="button" variant="secondary" onClick={() => { setError(''); setStep((current) => current - 1); }}>Back</Button>}{step < 5 ? <Button type="button" onClick={next}>Continue</Button> : <Button type="submit" disabled={loading}>{loading ? 'Generating' : 'Generate policy'}</Button>}</div></form>}</Card></PremiumGate></>;
}
