import { useState } from 'react';
import { Building, CreditCard, KeyRound, Mail, User } from 'lucide-react';
import { Alert, Button, Card, PageHeader, StatusBadge } from '../components/ui';
import { useAuth } from '../contexts/AuthContext';
import { usePortal } from '../contexts/PortalContext';

export default function Settings() {
  const { user, logout } = useAuth(); const { isPremium, subscriptionLoading } = usePortal(); const [billingLoading, setBillingLoading] = useState(false); const [error, setError] = useState('');
  const billing = async () => { setBillingLoading(true); setError(''); try { const response = await fetch(`${import.meta.env.VITE_API_URL}/api/billing/create-portal-session`, { credentials: 'include', method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ returnUrl: window.location.href }) }); const data = await response.json().catch(() => ({})); if (!response.ok || !data.url) throw new Error(data.error || 'Billing could not be opened.'); window.location.assign(data.url); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Billing could not be opened.'); setBillingLoading(false); } };
  const reset = async () => { await logout(); window.location.assign('/login'); };
  return <><PageHeader eyebrow="Workspace configuration" title="Settings" description="Review account, organisation, subscription, and security information backed by your account." />{error && <Alert tone="danger">{error}</Alert>}<div className="settings-grid"><Card className="workspace-card"><h2>Account</h2><div className="settings-row"><User /><span><small>Name</small><strong>{user?.fullName}</strong></span></div><div className="settings-row"><Mail /><span><small>Email</small><strong className="wrap-content">{user?.email}</strong></span></div><Button variant="secondary" onClick={() => { void reset(); }}><KeyRound size={16} /> Sign out</Button></Card><Card className="workspace-card"><h2>Organisation</h2><div className="settings-row"><Building /><span><small>Organisation</small><strong className="wrap-content">{user?.organizationName}</strong></span></div><div className="settings-row"><User /><span><small>Your role</small><strong>{user?.role}</strong></span></div></Card><Card className="workspace-card"><div className="workspace-card__header"><h2>Subscription</h2>{!subscriptionLoading && <StatusBadge tone={isPremium ? 'success' : 'neutral'}>{isPremium ? 'Active paid plan' : 'Free plan'}</StatusBadge>}</div><p className="muted">Billing changes are completed through Stripe’s secure customer portal.</p>{isPremium && <Button onClick={() => { void billing(); }} disabled={billingLoading}><CreditCard size={16} /> {billingLoading ? 'Opening billing' : 'Manage billing'}</Button>}</Card><Card className="workspace-card"><h2>Notifications and security</h2><p className="muted">No configurable notification preferences or additional security controls are implemented yet. No decorative toggles are shown.</p></Card></div></>;
}
