import { useEffect, useState } from 'react';
import type { FormEvent } from 'react';
import { UserPlus } from 'lucide-react';
import { Alert, Button, Card, DataTable, EmptyState, Input, Modal, PageHeader, Select, Skeleton, StatusBadge } from '../components/ui';
import { useAuth } from '../contexts/AuthContext';

type Teammate = { id: string; email: string; fullName: string; role: string; createdAt: string };
const API = import.meta.env.VITE_API_URL;

export default function Team() {
  const { user } = useAuth();
  const canManage = user?.role === 'ADMIN' || user?.role === 'SUPERADMIN';
  const [teammates, setTeammates] = useState<Teammate[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [open, setOpen] = useState(false); const [submitting, setSubmitting] = useState(false);
  const [form, setForm] = useState({ email: '', fullName: '', role: 'MEMBER' }); const [deliveryWarning, setDeliveryWarning] = useState(''); const [temporaryPassword, setTemporaryPassword] = useState('');
  const load = async () => { setLoading(true); setError(''); try { const response = await fetch(`${API}/api/team`, { credentials: 'include' }); const data = await response.json().catch(() => ([])); if (!response.ok) throw new Error(data.error || 'Team members could not be loaded.'); setTeammates(data); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Team members could not be loaded.'); } finally { setLoading(false); } };
  useEffect(() => { if (canManage) void load(); else setLoading(false); }, [canManage]);
  const add = async (event: FormEvent) => { event.preventDefault(); setSubmitting(true); setError(''); try { const response = await fetch(`${API}/api/team`, { credentials: 'include', method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'The team member could not be added.'); setTeammates((current) => [{ ...data, createdAt: new Date().toISOString() }, ...current]); setTemporaryPassword(data.temporaryPassword || ''); setDeliveryWarning(data.warning || ''); if (!data.temporaryPassword) { setOpen(false); setForm({ email: '', fullName: '', role: 'MEMBER' }); } } catch (caught) { setError(caught instanceof Error ? caught.message : 'The team member could not be added.'); } finally { setSubmitting(false); } };
  const remove = async (member: Teammate) => { if (!window.confirm(`Remove ${member.email} from your organisation?`)) return; const response = await fetch(`${API}/api/team/${member.id}`, { credentials: 'include', method: 'DELETE' }); if (response.status === 204) setTeammates((current) => current.filter((item) => item.id !== member.id)); else { const data = await response.json().catch(() => ({})); setError(data.error || 'The team member could not be removed.'); } };
  const close = () => { setOpen(false); setTemporaryPassword(''); setDeliveryWarning(''); setForm({ email: '', fullName: '', role: 'MEMBER' }); };
  return <><PageHeader eyebrow="Organisation access" title="Team" description="Manage people who can access your organisation workspace. Role and tenant checks are enforced by the API." actions={canManage ? <Button onClick={() => setOpen(true)}><UserPlus size={16} /> Add teammate</Button> : undefined} />{error && <Alert tone="danger">{error}</Alert>}{!canManage ? <Card><EmptyState title="Administrator access required" description="Only organisation administrators can view or manage team membership." /></Card> : loading ? <Skeleton label="Loading team members" /> : teammates.length === 0 ? <Card><EmptyState title="No teammates yet" description="Add a teammate when another person needs access to this organisation." /></Card> : <Card className="workspace-card"><DataTable headers={['Name', 'Email', 'Role', 'Joined', 'Actions']}>{teammates.map((member) => <tr key={member.id}><td>{member.fullName}</td><td className="wrap-content">{member.email}</td><td><StatusBadge tone={member.role === 'ADMIN' ? 'info' : 'neutral'}>{member.role}</StatusBadge></td><td>{new Date(member.createdAt).toLocaleDateString('en-GB')}</td><td><Button variant="danger" onClick={() => { void remove(member); }}>Remove</Button></td></tr>)}</DataTable></Card>}
    <Modal title={temporaryPassword ? 'Invitation delivery issue' : 'Add teammate'} open={open} onClose={close}>{temporaryPassword ? <div><Alert tone="warning">{deliveryWarning}</Alert><p>The temporary password is shown once because email delivery failed. Share it through a separate secure channel.</p><code className="one-time-value">{temporaryPassword}</code><div className="form-actions"><Button onClick={close}>Done</Button></div></div> : <form className="guided-form" onSubmit={add}><div><label htmlFor="team-name">Full name</label><Input id="team-name" value={form.fullName} onChange={(event) => setForm({ ...form, fullName: event.target.value })} required minLength={2} /></div><div><label htmlFor="team-email">Email</label><Input id="team-email" type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} required /></div><div><label htmlFor="team-role">Role</label><Select id="team-role" value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value })}><option value="MEMBER">Member</option><option value="ADMIN">Admin</option></Select></div><div className="form-actions"><Button type="button" variant="secondary" onClick={close}>Cancel</Button><Button type="submit" disabled={submitting}>{submitting ? 'Adding' : 'Add teammate'}</Button></div></form>}</Modal>
  </>;
}
